### ISSUE TITLE
Could not install. 

### ISSUE THREAD

**Issue by NuevoSer** [nellore/vickitrix#1]
Hi!

I tried to install and got this message:
Command "c:\users\XXXXX\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\XXXXX\\AppData\\Local\\Temp\\pip-build-y6k5rc_z\\pycrypto\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\XXXXX\AppData\Local\Temp\pip-ndtny__9-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\XXXXX\AppData\Local\Temp\pip-build-y6k5rc_z\pycrypto\

Attached is the complete log. Thanks for putting this together!
[error.txt](https://github.com/nellore/vickitrix/files/1120286/error.txt)

**Comment by nellore** [comment]
pycrypto is stubborn in Windows; see https://stackoverflow.com/questions/11405549/how-do-i-install-pycrypto-on-windows for installation advice. After getting that to work, retry ```pip install vickitrix```.

**Comment by nellore** [comment]
Talked to @NuevoSer offline; this fix works.
