### ISSUE TITLE
{inside_ask} is set once at the start of running the script, never updated (which leads to wrong limit orders)

### ISSUE THREAD

**Issue by Lasterie** [nellore/vickitrix#3]
I started the script, a tweet was triggered, a limit sell was placed at 2914,86.

A few minutes later, the price of BTC went up to 2930,67, a tweet was triggered, a limit sell was placed at - once again - 2914,86. That's a problem, because now I sell at a too low price.

**Comment by nellore** [comment]
As far as I can tell, the code always gets the product order book anew when a rule is being executed. `{inside_ask}` is not set once at the start of running the script; see https://github.com/nellore/vickitrix/blob/master/vickitrix/__init__.py#L186 . It could indeed be that the inside ask did not change on GDAX.

Thanks for helping debug `vickitrix`. I'm closing this issue for now, but I'll reopen if there does turn out to be something wrong.
